Repository TableauBits/Yatga, pull requests merged in 2022-02, with the labels that each got.

#34 Personnalisation de l'onglet du site
  src/favicon.ico
  src/index.html
Labels: minor

#35 Filtre sur les chansons
  src/app/app.module.ts
  src/app/components/constitution-page/constitution.component.html
  src/app/components/constitution-page/constitution.component.scss
  src/app/components/constitution-page/song-list/song-list.component.html
  src/app/components/constitution-page/song-list/song-list.component.scss
  src/app/components/constitution-page/song-list/song-list.component.ts
  src/app/components/constitution-page/votes/votes-grade/votes-grade.component.html
  src/app/components/constitution-page/votes/votes-grade/votes-grade.component.scss
  src/app/components/constitution-page/votes/votes-grade/votes-grade.component.ts
  src/app/types/song.ts
  src/styles.scss
Labels: enhancement, ui, minor

#38 Ajout des infos de deploy
  .firebaserc
  .gitignore
  firebase.json
Labels: minor

#36 Rejoindre une constitution
  package.json
  src/app/app.module.ts
  src/app/components/admin-page/admin-page.component.html
  src/app/components/admin-page/new-constitution/new-constitution.component.html
  src/app/components/join-constitution/join-constitution.component.html
  src/app/components/join-constitution/join-constitution.component.scss
  src/app/components/join-constitution/join-constitution.component.spec.ts
  src/app/components/join-constitution/join-constitution.component.ts
  src/app/components/navbar/navbar.component.html
  src/app/components/navbar/navbar.component.ts
  src/styles.scss
Labels: enhancement, minor

#42 Amélioration de la navigation dans la soirée électorale
  src/app/app.module.ts
  src/app/components/constitution-page/results/results-grade/grade-electoral/grade-electoral.component.html
  src/app/components/constitution-page/results/results-grade/grade-electoral/grade-electoral.component.scss
  src/app/components/constitution-page/results/results-grade/grade-electoral/grade-electoral.component.ts
  src/app/components/constitution-page/results/results-grade/grade-grades/grade-grades.component.ts
  src/app/components/constitution-page/results/results-grade/grade-navigator/grade-navigator.component.html
  src/app/components/constitution-page/results/results-grade/grade-navigator/grade-navigator.component.scss
  src/app/components/constitution-page/results/results-grade/grade-navigator/grade-navigator.component.spec.ts
  src/app/components/constitution-page/results/results-grade/grade-navigator/grade-navigator.component.ts
  src/app/components/constitution-page/results/results-grade/grade-ranking/grade-ranking.component.ts
  src/app/components/constitution-page/results/results-grade/results-grade.component.ts
  src/app/types/firework.ts
Labels: ui, minor
