Repository TableauBits/Yatga, pull requests merged in 2022-09, with the labels that each got.

#73 Refactorisation des votes pour permettre de voter pendant l'ajout de chansons
  package-lock.json
  package.json
  src/app/components/constitution-page/constitution.component.ts
  src/app/components/constitution-page/random-song/random-song.component.ts
  src/app/components/constitution-page/song-list/song-list.component.ts
  src/app/components/constitution-page/song-list/song-navigator/song-navigator.component.ts
  src/app/components/constitution-page/votes/votes-grade/vote-navigator/vote-navigator.component.ts
  src/app/components/constitution-page/votes/votes-grade/votes-grade.component.html
  src/app/components/constitution-page/votes/votes-grade/votes-grade.component.ts
  src/app/services/auth.service.ts
Labels: enhancement, ui, minor

#74 Mise à jours en temps réel du pop-up "Gérer mes chansons"
  src/app/components/constitution-page/constitution.component.ts
  src/app/components/constitution-page/manage-songs/manage-songs.component.ts
Labels: bug, patch

#75 Correction pour 8ème Xénocratie
  src/app/components/admin-page/new-constitution/new-constitution.component.scss
  src/app/components/constitution-page/constitution.component.html
  src/app/components/constitution-page/manage-songs/manage-songs.component.html
  src/app/components/constitution-page/results/results-favorites/results-favorites.component.scss
  src/app/components/constitution-page/results/results-grade/grade-average/grade-average.component.html
  src/app/components/constitution-page/results/results-grade/grade-average/grade-average.component.scss
  src/app/components/constitution-page/results/results-grade/grade-average/grade-average.component.ts
  src/app/components/constitution-page/results/results-grade/grade-electoral/grade-electoral.component.html
  src/app/components/constitution-page/results/results-grade/grade-electoral/grade-electoral.component.scss
  src/app/components/constitution-page/results/results-grade/grade-grades/grade-grades.component.html
  src/app/components/constitution-page/results/results-grade/grade-grades/grade-grades.component.scss
  src/app/components/constitution-page/results/results-grade/grade-profile/grade-profile.component.html
  src/app/components/constitution-page/results/results-grade/grade-ranking/grade-ranking.component.html
  src/app/components/constitution-page/song-list/song-list.component.html
  src/app/components/constitution-page/song-list/song-list.component.scss
  src/app/components/constitution-page/votes/votes-grade/votes-grade.component.html
  src/app/components/constitution-page/votes/votes-grade/votes-grade.component.scss
  src/styles.scss
Labels: ui, patch

#78 Future Funk: Hotfix 1
  src/app/components/constitution-page/export/export.component.scss
  src/app/components/constitution-page/song-list/song-navigator/song-navigator.component.html
  src/app/components/constitution-page/song-list/song-navigator/song-navigator.component.scss
  src/app/components/constitution-page/song-list/song-navigator/song-navigator.component.ts
  src/app/components/constitution-page/votes/votes-grade/vote-navigator/vote-navigator.component.html
  src/app/components/constitution-page/votes/votes-grade/vote-navigator/vote-navigator.component.scss
Labels: bug, patch

#80 Future Funk: Hotfix 1
  .github/workflows/firebase-hosting-merge.yml
  firebase.json
  package.json
  src/app/components/constitution-page/export/export.component.scss
  src/app/components/constitution-page/song-list/song-navigator/song-navigator.component.html
  src/app/components/constitution-page/song-list/song-navigator/song-navigator.component.scss
  src/app/components/constitution-page/song-list/song-navigator/song-navigator.component.ts
  src/app/components/constitution-page/votes/votes-grade/vote-navigator/vote-navigator.component.html
  src/app/components/constitution-page/votes/votes-grade/vote-navigator/vote-navigator.component.scss
Labels: bug, patch

#81 Correction du bouton Réinitialiser pour le classement dans la Zone Électorale.
  src/app/components/constitution-page/votes/votes-grade/votes-grade.component.html
  src/app/components/constitution-page/votes/votes-grade/votes-grade.component.ts
Labels: bug, patch

#82 Ajout des releases Github sur la Home Page
  src/app/components/home-page/home-page.component.html
  src/app/components/home-page/home-page.component.scss
  src/app/components/home-page/home-page.component.ts
  src/styles.scss
Labels: minor

#85 Correction de l'utilisation de l'opérateur OR dans un switch-case
  src/app/components/constitution-page/constitution.component.ts
  src/app/components/constitution-page/manage-songs/manage-songs.component.ts
Labels: patch

#83 Mise à jour vers Angular 13
  .eslintrc.json
  .gitignore
  .npmrc
  angular.json
  package-lock.json
  package.json
  pnpm-lock.yaml
  src/app/app.module.ts
  src/app/components/invite-page/invite-page.component.ts
  src/app/services/auth.service.ts
  src/polyfills.ts
  src/test.ts
  tslint.json
Labels: major
