Repository TableauBits/Yatga, pull requests merged in 2023-08, with the labels that each got.

#120 Ajout support peertube
  package-lock.json
  package.json
  src/app/components/constitution-page/manage-songs/manage-songs.component.ts
  src/app/services/get-url.service.ts
  src/app/types/url.ts
  src/assets/icons/peertube.png
Labels: bug, enhancement

#116 Support du champ `languages` d'une chanson
  package-lock.json
  package.json
  src/app/components/constitution-page/manage-songs/manage-songs.component.html
  src/app/components/constitution-page/manage-songs/manage-songs.component.scss
  src/app/components/constitution-page/manage-songs/manage-songs.component.ts
  src/app/components/constitution-page/optionnal-song-infos-button/optionnal-song-infos-button.component.html
  src/app/components/constitution-page/optionnal-song-infos-button/optionnal-song-infos-button.component.ts
  src/app/components/constitution-page/results/results-grade/grade-ranking/grade-ranking.component.html
  src/app/types/song-utils.ts
  src/app/types/utils.ts
Labels: enhancement

#112 Recolaration et restructuration graphique du site
  src/app/components/admin-page/admin-page.component.html
  src/app/components/admin-page/manage-invites/manage-invites.component.html
  src/app/components/admin-page/manage-roles/manage-roles.component.html
  src/app/components/admin-page/new-constitution/new-constitution.component.html
  src/app/components/constitution-page/constitution.component.html
  src/app/components/constitution-page/constitution.component.scss
  src/app/components/constitution-page/export/export.component.html
  src/app/components/constitution-page/manage-songs/manage-songs.component.html
  src/app/components/constitution-page/parameters/parameters.component.html
  src/app/components/constitution-page/random-song/random-song.component.html
  src/app/components/constitution-page/results/results-grade/grade-electoral/grade-electoral.component.html
  src/app/components/constitution-page/results/results-grade/grade-profile/grade-profile.component.html
  src/app/components/constitution-page/song-list/song-list.component.scss
  src/app/components/constitution-page/song-list/song-navigator/song-navigator.component.html
  src/app/components/constitution-page/votes/votes-grade/vote-navigator/vote-navigator.component.html
  src/app/components/current-constitution-page/current-constitution-page.component.html
  src/app/components/current-constitution-page/current-constitution-page.component.scss
  src/app/components/delete-song-warning/delete-song-warning.component.html
  src/app/components/home-page/home-page.component.html
  src/app/components/home-page/home-page.component.scss
  src/app/components/invite-page/invite-page.component.html
  src/app/components/join-constitution/join-constitution.component.html
  src/app/components/join-constitution/join-constitution.component.scss
  src/app/components/navbar/navbar.component.html
  src/app/components/navbar/navbar.component.scss
  src/app/components/profile-page/profile-page.component.html
  src/app/components/users-page/users-page.component.html
  src/app/components/users-page/users-page.component.scss
  src/styles.scss
  src/styles/variables.scss
Labels: ui

#122 Correction de l'utilisation des graphes avec le passage d'un id
  src/app/components/constitution-page/results/results-favorites/results-favorites.component.html
  src/app/components/constitution-page/results/results-grade/grade-average/grade-average.component.html
  src/app/components/constitution-page/results/results-grade/grade-electoral/grade-electoral.component.html
  src/app/components/constitution-page/results/results-grade/grade-grades/grade-grades.component.html
  src/app/components/constitution-page/results/results-grade/grade-profile/grade-profile.component.html
  src/app/components/constitution-page/results/results-grade/grade-ranks/grade-ranks.component.html
  src/app/components/constitution-page/results/results-grade/grade-relationship/grade-relationship.component.html
  src/app/components/constitution-page/votes/votes-grade/votes-grade.component.html
  src/app/components/template/chord/chord.component.html
  src/app/components/template/chord/chord.component.ts
  src/app/components/template/heatmap/heatmap.component.html
  src/app/components/template/heatmap/heatmap.component.ts
  src/app/components/template/histogram/histogram.component.html
  src/app/components/template/histogram/histogram.component.ts
  src/app/components/template/pie/pie.component.html
  src/app/components/template/pie/pie.component.ts
  src/app/components/template/radar/radar.component.html
  src/app/components/template/radar/radar.component.ts
  src/app/components/template/scatter/scatter.component.html
  src/app/components/template/scatter/scatter.component.ts
  src/app/types/charts.ts
Labels: bug, patch

#123 Redimensionnement automatique des graphes
  src/app/components/template/chord/chord.component.html
  src/app/components/template/heatmap/heatmap.component.html
  src/app/components/template/histogram/histogram.component.html
  src/app/components/template/pie/pie.component.html
  src/app/components/template/radar/radar.component.html
  src/app/components/template/scatter/scatter.component.html
  src/app/types/charts.ts
Labels: bug, ui, patch

#124 Ajout de la valeur "Instrumental" comme langue
  src/app/components/constitution-page/manage-songs/manage-songs.component.html
  src/app/components/constitution-page/manage-songs/manage-songs.component.scss
  src/app/components/constitution-page/manage-songs/manage-songs.component.ts
  src/app/components/navbar/navbar.component.html
  src/app/types/song-utils.ts
  src/app/types/utils.ts
Labels: bug, patch

#125 Ajout de la sous-section "Constitution" dans la page des résultats
  src/app/app.module.ts
  src/app/components/constitution-page/optionnal-song-infos-button/optionnal-song-infos-button.component.ts
  src/app/components/constitution-page/results/results-constitution/results-constitution.component.html
  src/app/components/constitution-page/results/results-constitution/results-constitution.component.scss
  src/app/components/constitution-page/results/results-constitution/results-constitution.component.spec.ts
  src/app/components/constitution-page/results/results-constitution/results-constitution.component.ts
  src/app/components/constitution-page/results/results-grade/grade-grades/grade-grades.component.html
  src/app/components/constitution-page/results/results-grade/grade-grades/grade-grades.component.ts
  src/app/components/constitution-page/results/results-grade/grade-profile/grade-profile.component.html
  src/app/components/constitution-page/results/results-grade/grade-profile/grade-profile.component.ts
  src/app/components/constitution-page/results/results-grade/results-grade.component.html
  src/app/components/constitution-page/results/results-grade/results-grade.component.ts
  src/app/components/constitution-page/votes/votes-grade/votes-grade.component.html
  src/app/components/constitution-page/votes/votes-grade/votes-grade.component.ts
  src/app/components/template/histogram/histogram.component.ts
  src/app/types/song-utils.ts
Labels: enhancement, result

#126 Ajout de la répartition des langues des chansons dans la section des résultat.
  src/app/components/constitution-page/results/results-constitution/results-constitution.component.html
  src/app/components/constitution-page/results/results-constitution/results-constitution.component.ts
  src/app/types/charts.ts
  src/styles/echarts-theme.json
Labels: enhancement, result

#127 Refactoring des navigateurs avec la classe `NavigatorSongDisplayComponent`
  src/app/app.module.ts
  src/app/components/constitution-page/constitution.component.ts
  src/app/components/constitution-page/navigator-song-display/navigator-song-display.component.html
  src/app/components/constitution-page/navigator-song-display/navigator-song-display.component.scss
  src/app/components/constitution-page/navigator-song-display/navigator-song-display.component.spec.ts
  src/app/components/constitution-page/navigator-song-display/navigator-song-display.component.ts
  src/app/components/constitution-page/random-song/random-song.component.html
  src/app/components/constitution-page/random-song/random-song.component.ts
  src/app/components/constitution-page/results/results-grade/grade-profile/grade-profile.component.ts
  src/app/components/constitution-page/song-list/song-list.component.ts
  src/app/components/constitution-page/song-list/song-navigator/song-navigator.component.html
  src/app/components/constitution-page/song-list/song-navigator/song-navigator.component.ts
  src/app/components/constitution-page/votes/votes-grade/vote-navigator/vote-navigator.component.html
  src/app/components/constitution-page/votes/votes-grade/vote-navigator/vote-navigator.component.ts
  src/app/components/constitution-page/votes/votes-grade/votes-grade.component.ts
  src/app/components/template/histogram/histogram.component.ts
  src/styles.scss
Labels: enhancement, ui, internal

#128 Révision de l'interface des cards
  src/app/app.module.ts
  src/app/components/constitution-page/optionnal-song-infos-button/optionnal-song-infos-button.component.html
  src/app/components/constitution-page/optionnal-song-infos-button/optionnal-song-infos-button.component.ts
  src/app/components/constitution-page/song-list/song-list.component.html
  src/app/components/constitution-page/song-list/song-list.component.scss
  src/app/components/constitution-page/votes/votes-grade/votes-grade.component.html
  src/app/components/constitution-page/votes/votes-grade/votes-grade.component.scss
Labels: ui, minor

#129 Séparation des constitutions en fonction de si elles sont en cours ou terminées
  src/app/components/current-constitution-page/current-constitution-page.component.html
  src/app/components/current-constitution-page/current-constitution-page.component.scss
  src/app/components/current-constitution-page/current-constitution-page.component.ts
Labels: ui

#131 Mise à jour des versions de `package.json` et `package-lock.json`
  package-lock.json
  package.json
Labels: patch

#133 Ajout d'un graph pour visualiser l'ajout des chansons d'une constitution dans le temps
  src/app/app.module.ts
  src/app/components/constitution-page/results/results-constitution/results-constitution.component.html
  src/app/components/constitution-page/results/results-constitution/results-constitution.component.ts
  src/app/components/template/calendar/calendar.component.html
  src/app/components/template/calendar/calendar.component.scss
  src/app/components/template/calendar/calendar.component.spec.ts
  src/app/components/template/calendar/calendar.component.ts
  src/app/components/template/heatmap/heatmap.component.ts
  src/app/types/charts.ts
  src/styles/echarts-theme.json
Labels: enhancement, minor, result
