Repository TableauBits/Yatga, pull requests merged in 2023-09, with the labels that each got.

#134 Ajout d'un service `SongPropertyManagerService`
  src/app/components/admin-page/new-constitution/new-constitution.component.ts
  src/app/components/constitution-page/navigator-song-display/navigator-song-display.component.html
  src/app/components/constitution-page/navigator-song-display/navigator-song-display.component.scss
  src/app/components/constitution-page/navigator-song-display/navigator-song-display.component.ts
  src/app/components/constitution-page/parameters/parameters.component.html
  src/app/components/constitution-page/parameters/parameters.component.scss
  src/app/components/constitution-page/parameters/parameters.component.ts
  src/app/components/constitution-page/results/results-grade/grade-electoral/grade-electoral.component.html
  src/app/components/constitution-page/results/results-grade/grade-electoral/grade-electoral.component.scss
  src/app/components/constitution-page/results/results-grade/grade-electoral/grade-electoral.component.ts
  src/app/components/constitution-page/song-list/song-list.component.html
  src/app/components/constitution-page/song-list/song-list.component.scss
  src/app/components/constitution-page/song-list/song-navigator/song-navigator.component.ts
  src/app/components/constitution-page/votes/votes-grade/votes-grade.component.html
  src/app/components/constitution-page/votes/votes-grade/votes-grade.component.scss
  src/app/components/constitution-page/votes/votes-grade/votes-grade.component.ts
  src/app/services/song-property-manager.service.ts
  src/app/types/local-storage.ts
Labels: enhancement, minor

#135 Aide pour rechercher les informations supplémentaires des chansons
  src/app/components/constitution-page/manage-songs/manage-songs.component.html
  src/app/components/constitution-page/manage-songs/manage-songs.component.scss
  src/app/components/constitution-page/manage-songs/manage-songs.component.ts
  src/assets/icons/apple_music.png
  src/assets/icons/discogs.png
  src/assets/icons/genius.png
  src/assets/icons/spotify.png
Labels: enhancement, minor

#136 Ajout du site LastFM à la liste des sites de recherche
  src/app/components/constitution-page/manage-songs/manage-songs.component.ts
  src/assets/icons/lastfm.png
Labels: enhancement, minor

#140 Révision de la page des utilisateurs
  src/app/components/users-page/users-page.component.html
  src/app/components/users-page/users-page.component.scss
Labels: ui, patch

#139 Correction du bouton "Regarder la vidéo sur le site d'origine" pour les cards de la section des votes
  src/app/components/constitution-page/song-list/song-list.component.html
  src/app/components/constitution-page/song-list/song-list.component.ts
  src/app/components/constitution-page/votes/votes-grade/votes-grade.component.html
  src/app/services/song-property-manager.service.ts
Labels: bug, patch

#141 Ajout de la langue "Autre"
  src/app/components/constitution-page/manage-songs/manage-songs.component.html
  src/app/components/constitution-page/manage-songs/manage-songs.component.ts
  src/app/types/song-utils.ts
Labels: enhancement, patch

#142 Correction de l'affichage des votes sur les cards
  src/app/components/constitution-page/song-list/song-list.component.html
  src/app/components/constitution-page/song-list/song-list.component.scss
  src/app/components/constitution-page/votes/votes-grade/votes-grade.component.html
  src/app/components/constitution-page/votes/votes-grade/votes-grade.component.scss
Labels: bug, patch

#144 Utilisation d'une configuration pour les Scatter Graph
  src/app/components/constitution-page/results/results-grade/grade-ranks/grade-ranks.component.html
  src/app/components/constitution-page/results/results-grade/grade-ranks/grade-ranks.component.ts
  src/app/components/template/scatter/scatter.component.ts
  src/app/types/charts.ts
Labels: bug, patch, internal

#145 Suppression des dépendances dupliquées
  .gitignore
  package.json
Labels: bug, internal

#146 Ajout de la répartition des notes en fonction des langues
  src/app/components/constitution-page/results/results-grade/grade-grades/grade-grades.component.html
  src/app/components/constitution-page/results/results-grade/grade-grades/grade-grades.component.ts
  src/app/components/constitution-page/results/results-grade/grade-ranks/grade-ranks.component.ts
  src/app/types/charts.ts
Labels: enhancement, minor, result

#147 Adaptation de l'affichage des résultats en fonction de la présence ou non de données optionnelles.
  src/app/components/constitution-page/results/results-constitution/results-constitution.component.html
  src/app/components/constitution-page/results/results-constitution/results-constitution.component.ts
Labels: enhancement, patch, result

#149 Affichage de l'année moyenne et médiane des chansons
  src/app/components/constitution-page/results/results-constitution/results-constitution.component.html
  src/app/components/constitution-page/results/results-constitution/results-constitution.component.ts
  src/app/types/math.ts
Labels: enhancement, patch, result
